import React, { useState, useEffect } from "react";
import { useParams } from "react-router-dom";
import PayslipList from "./PayslipList";
import PayslipDetails from "./PayslipDetails";
import DTRViewer from "./DTRViewer";
import { PayrollResult, DTREntry } from "../../types/types";
import * as DTRService from "../../services/dtr";
import * as PayrollService from "../../services/payroll";
import * as EmployeeService from "../../services/employee";

const EmployeeDashboard = () => {
  const { employee_id } = useParams<{ employee_id: string }>();
  const [payslips, setPayslips] = useState<PayrollResult[]>([]);
  const [dtrEntries, setDtrEntries] = useState<DTREntry[]>([]);
  const [employee, setEmployee] = useState<DTREntry[]>([]);
  const [selectedPayslip, setSelectedPayslip] = useState<PayrollResult | null>(
    null
  );
  const [selectedMonth, setSelectedMonth] = useState<string | null>(null);

  useEffect(() => {
    // Fetch payslips generated by HR for this employee
    const fetchPayslips = async () => {
      const data = await PayrollService.getEmployeePayslips(employee_id);
      setPayslips(data);
    };

    // Fetch DTR entries for this employee
    const fetchDTR = async () => {
      const data = await PayrollService.getEmployeeDTR(employee_id);
      setDtrEntries(data);
    };

    const fetchEmployee = async () => {
      const data = await EmployeeService.getEmployee(employee_id);
      setEmployee(data);
    };

    // fetchEmployee();
    fetchPayslips();
    fetchDTR();
  }, [employee_id]);

  const handleMonthClick = (month: string) => {
    setSelectedMonth(month);
    const payslip = payslips.find((p) => p.pay_period_start.startsWith(month));
    if (payslip) setSelectedPayslip(payslip);
  };

  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-6">Employee Dashboard</h1>

      <div className="mb-8">
        <h2 className="text-xl font-semibold mb-2">Your Payslips</h2>
        <PayslipList payslips={payslips} onSelectMonth={handleMonthClick} />
      </div>

      {selectedMonth && (
        <div className="mb-8">
          <h2 className="text-xl font-semibold mb-2">
            DTR for {selectedMonth}
          </h2>
          <DTRViewer dtrEntries={dtrEntries} month={selectedMonth} />
        </div>
      )}

      {selectedPayslip && (
        <PayslipDetails
          payslip={selectedPayslip}
          onClose={() => setSelectedPayslip(null)}
        />
      )}
    </div>
  );
};

export default EmployeeDashboard;
